
# Site details
lang: en-GB
host: rowanmanning.com
email: info@rowanmanning.com

# Tracking info
track:
  ga: UA-5860182-1
  bitly: 9fa4195591f6

# Jekyll config
exclude:
  - bower.json
  - CNAME
  - Makefile
  - README.md
future: false
lsi: false
permalink: /posts/:title/
pygments: true
safe: true
timezone: Europe/London
