
# Jekyll config
auto: true
exclude:
  - CNAME
  - Makefile
  - README.md
lsi: false
permalink: /posts/:title/
pygments: true
safe: true
server: true

# Site details
lang: en-GB
host: rowanmanning.com
email: info@rowanmanning.com
twitter: rowanmanning

# Blog details
blog:
  title: Rowan Manning's Blog
  feed: http://rowanmanning.com/blog.xml

# Author details
author:
  name: Rowan Manning
  url: http://rowanmanning.com/

# Tracking info
track:
  ga: UA-5860182-1
  bitly: 9fa4195591f6

# Social media
social:

  - type: twitter
    url: https://twitter.com/rowanmanning
    label: Twitter
    title: Rowan Manning on Twitter
    nav: true

  - type: github
    url: https://github.com/rowanmanning
    label: GitHub
    title: Rowan Manning's Open-Source Code on GitHub
    nav: true

  - type: dribbble
    url: http://dribbble.com/rowanmanning
    label: Dribbble
    title: Rowan Manning's Design Work on Dribbble
    nav: true

  - type: linkedin
    url: http://www.linkedin.com/in/rowanmanning
    label: LinkedIn
    title: Rowan Manning's Professional Profile on LinkedIn

  - url: https://plus.google.com/112029391894332163375
    hidden: true
