
# Files and directories to exclude from compilation
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md

# Extensions to use
gems:
  - jekyll-sitemap

# Whether to publish future posts
future: false

# Source code highlighter
highlighter: pygments

# Don't produce an index for related posts
lsi: false

# Markdown parser
markdown: kramdown

# Post permalink format
permalink: /posts/:title/

# Sass compilation
sass:
  sass_dir: asset/style
  style: :compressed

# Timezone setting
timezone: Europe/London
