
# Jekyll config
auto: true
exclude:
  - CNAME
  - Makefile
  - README.md
lsi: false
permalink: /posts/:title/
pygments: true
safe: true
server: true

# Site details
lang: en-GB
host: rowanmanning.com

# Blog details
blog:
  title: Rowan Manning's Blog

# Author details
author:
  name: Rowan Manning
  url: http://rowanmanning.com/

# Tracking info
track:
  ga: UA-5860182-1
  bitly: 9fa4195591f6
