
# Files and directories to exclude from compilation
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md

# Extensions to use
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Post permalink format
permalink: /posts/:title/

# Sass compilation
sass:
  sass_dir: asset/style
  style: :compressed

# Timezone setting
timezone: Europe/London
